services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    networks:
      - mern-network
  backend:
    build: ./backend
    ports:
      - "5050:5050"
    networks:
      - mern-network
    depends_on:
      - mongo
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - mern-network
    volumes:
      - mongo-data:/data/db

networks:
  mern-network:
    driver: bridge
volumes:
  mongo-data:
    driver: local
